name: Nightly Release
on:
  # This can be used to automatically publish nightlies at UTC nighttime
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC
  # This can be used to allow manually triggering nightlies from the web interface
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_RELEASE_ID: 179589950

permissions:
  contents: write

jobs:
  nightly-server:
    if: ${{ github.repository == vars.REPO_MAIN }}
    name: Deploy server nightly
    strategy:
      fail-fast: false
      matrix:
        arch: [x64, arm64]
        include:
          - arch: x64
            runs-on: ubuntu-22.04
          - arch: arm64
            runs-on: ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v6

      - name: Run the build
        uses: ./.github/actions/build-server
        with:
          os: linux
          arch: ${{ matrix.arch }}

      - name: Publish release
        uses: softprops/action-gh-release@v2.5.0
        if: ${{ github.event_name != 'pull_request' }}
        with:
          make_latest: false
          prerelease: true
          draft: false
          fail_on_unmatched_files: true
          files: upload/*.*
          tag_name: nightly
          name: Nightly Build
